---
- name: Install Apache.
  apt: name={{ item }} state=present
  with_items:
    - apache2-mpm-worker
    - apache2-suexec
    - libapache2-mod-fcgid
- name: Enable required modules
  apache2_module: name={{ item }} state=present
  with_items:
    - rewrite
    - fcgid
    - suexec
    - include
  notify: restart apache
- name: Fix fcgid.conf.
  copy:
    src: "files/fcgid.conf"
    dest: "/etc/apache2/mods-available/fcgid.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
- name: Create wrapper Script for PHP.
  copy:
    src: "files/php-fcgi-starter"
    dest: "/var/www/{{ domain }}/scripts/php-fcgi-starter"
    owner: "{{ domain }}"
    group: vhosts
    mode: 0755
- name: Add VirtualHost.
  template:
    src: "template/vhost.conf.j2"
    dest: "/etc/apache2/sites-available/{{domain}}.conf"
    owner: root
    group: root
    mode: 0644
- name: Symlink VirtualHost to site-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ domain }}.conf"
    state: link
  notify: restart apache
- name: Remove default VirtualHost file.
  file:
    path: "/etc/apache2/sites-enabled/000-default"
    state: absent
  notify: restart apache
- name: Make sure Apache is started and now and at boot.
  service: name=apache2 state=started #enabled=yes
